
[functions.submit-score]
enabled = true
verify_jwt = false
import_map = "./functions/submit-score/deno.json"
entrypoint = "./functions/submit-score/index.ts"

[functions.register-pupil]
enabled = true
verify_jwt = false
import_map = "./functions/register-pupil/deno.json"
entrypoint = "./functions/register-pupil/index.ts"

[functions.teacher-ops]
enabled = true
verify_jwt = false
import_map = "./functions/teacher-ops/deno.json"
entrypoint = "./functions/teacher-ops/index.ts"
